### ISSUE TITLE
Feature Request: Notification on CD improvements 

### ISSUE THREAD

**Issue by jayzalowitz** [Shopify/shipit-engine#1074]
In the ideal situation, it would be great to get notfications on slack or email based on tags, another option would be emailing the commit owner.
In the ideal situation web push notifications would be great for deployments.

**Comment by benlangfeld** [comment]
You can implement all of these in the application that you wrap Shipit in. That’s probably the best place due to the variety.

**Comment by jayzalowitz** [comment]
@benlangfeld while I would say thats probably not horrible, I do believe a web push notification is probably a huge win for everyone here.

**Comment by casperisfine** [comment]
I understand how this is appealing, and as a matter of fact we did implement deploy notifications in Slack channels. The problem [as outlined years ago](https://github.com/Shopify/shipit-engine/pull/198) is that there's dozens of different ways to do this, and it is extremely tied to the organization.

So it would be the source of a lot of complexity in Shipit, would probably only work for a small subset of its users, and generate a lot of feature requests.

That's why we decided that this is to be done either in the host application, or using webhooks sent to a chatbot. Shipit already sends webhooks that are specially crafted to easily build chat notifications.
