### ISSUE TITLE
[Proposal] Collect deployment 'Failure Reasons'

### ISSUE THREAD

**Issue by ryanmrodriguez** [Shopify/shipit-engine#1076]
We would like to have the ability to classify and submit 'reasons' for failed deployments. Our goal ultimately is to have greater visibility on these failures for our own metrics. 

Before we build this out, we would like your feedback on the initial concept. The basic idea would be to add some extra inputs on the deployment page when that deployment has failed. 

Questions:
- Would this be something that you would consider accepting into Shipit?
- What would be the preferred way to handle additional datapoints?

I have attached some screenshots of the initial concept. Thanks!

<img width="1537" alt="base" src="https://user-images.githubusercontent.com/62253265/83906276-e58d6200-a728-11ea-95ac-c39d40ef9667.png">
<img width="1539" alt="dropdown" src="https://user-images.githubusercontent.com/62253265/83906280-e8885280-a728-11ea-8729-66ebf140db66.png">
<img width="1538" alt="missing_dep" src="https://user-images.githubusercontent.com/62253265/83906286-ec1bd980-a728-11ea-92f7-99f04f9d1856.png">
<img width="1543" alt="other_blank" src="https://user-images.githubusercontent.com/62253265/83906299-f0e08d80-a728-11ea-98cc-6179c3073ade.png">
<img width="1539" alt="other_typed" src="https://user-images.githubusercontent.com/62253265/83906308-f3db7e00-a728-11ea-95bc-4ed82ffe4004.png">

**Comment by casperisfine** [comment]
> Would this be something that you would consider accepting into Shipit?

Not sure. I feel like this classification would be fairly dependent on each installation and the type of software you often deploy. Or we'd need to make the categories entirely dynamic, which means even more complexity.

But I guess I could be convinced otherwise by a use case that would suits a large proportion of Shipit users.

However I'd be interested in making this cleanly implementable. There is already a "plugin" system that allows to load arbitrary JS & CSS in the task output page, and it's fairly easy to add custom controllers to the host app. So it wouldn't be too hard to implement this already, I think the only thing missing would be to add a setting to have a list of plugin enabled globally.

> What would be the preferred way to handle additional datapoints?

In your host app you can do what you want. Either add a column to `tasks` (simple for risk of name clashes in the future) or add another model with a `1:1` relationship to `tasks`.
