### ISSUE TITLE
Fetch public repos via HTTPS

### ISSUE THREAD

**Issue by byroot** [Shopify/shipit-engine#360]
Public repos an be fetched by anyone, but still requires the SSH key of a github account.

For people deploying only public repos, using HTTPS would simplify things.

It mean adding a public column, and fetching that info.

cc @dwradcliffe

**Comment by dwradcliffe** [comment]
If we do #366 we might not need this.

**Comment by gmalette** [comment]
I think this is a good idea. It would allow deploying projects that the Shipit owner does not own, too. However, we would not be able to setup webhooks in that case, so we'd probably need something that automatically polls for status updates and such

**Comment by casperisfine** [comment]
Some experimentation I did today.

Now that we fully converted to a GitHub App, we can actually use the App token for git operations, e.g: `git clone 'https://git:<token>@github.com/org/repo.git'`.

But off course we don't want to specify it like this, because it would be displayed in the command output and stored in the `.git/config`. So it would be both leaked, and would break once the token expires.

However you can tell git to ask the password to another program with the `GIT_ASKPASS` env var, which would allow to securely pass the token to git.

So thanks to this, I think we can 100% migrate to `https` cloning, which means we'd no longer need a real github user with SSH keys & all that. 

I'll work on this tomorrow, cc @DazWorrall, @wvanbergen

**Comment by wvanbergen** [comment]
Neat, this is cool.

**Comment by DazWorrall** [comment]
For bonus points: are the app tokens short lived? Currently we can completely hide the private key from deploy scripts, whereas `GIT_ASKPASS` will provide a mechanism to expose credentials. If they're time limited then that would greatly mitigate the risk of a leaked token.

**Comment by wvanbergen** [comment]
When using a Github app, the tokens are valid for one hour.
