### ISSUE TITLE
Test suite doesn't pass with sqlite3

### ISSUE THREAD

**Issue by byroot** [Shopify/shipit-engine#403]
See https://travis-ci.org/rafaelfranca/shipit-engine/jobs/64195221 for example.

I think it's because of the way string comparison works (case sensitivity) but not 100% sure. 

cc @rafaelfranca

**Comment by rafaelfranca** [comment]
It is because of milliseconds on the `created_at` comparison of this line https://github.com/Shopify/shipit-engine/blob/ffcd5abad91a97e1950bd0922dd89126f0c5d011/app/models/status.rb#L21.

I have a feeling that it is a Rails bug, so I'm writing a reproduction script to isolate the problem.

(BTW, `test_after_commit` gem is broken when using Rails' 4-2-stable branch, it is related to `sync_with_transaction_state cc @arthurnn)

```
NoMethodError: undefined method `[]=' for nil:NilClass
    test_after_commit (0.4.0) lib/test_after_commit.rb:57:in `sync_with_transaction_state'
```

**Comment by byroot** [comment]
Great catch! We could probably strip milliseconds as a temporary workaround.

**Comment by rafaelfranca** [comment]
Ok. Found the problem. I'll open a PR shortly
