### ISSUE TITLE
Add dynamic "confirm" step before deploy

### ISSUE THREAD

**Issue by wvanbergen** [Shopify/shipit-engine#426]
A "confirm" step would be really useful to make sure it's safe to deploy. The content to display would be collecting by running a task on the source code. The main use case for me is to show a list of pending changes, so you know nothing crazy will happen when you deploy.

#### Process

1. Checkout SHA
2. Run a task as defined in shipit.yml
3. Capture output of said task, and display to user.
4. User can press **Continue** or **Abort** [1]
5. **Continue** will continue with the normal deploy procedure

[1] Potentially, if the task returns a non-zero status, the "Continue" button could be disabled. 

#### Examples

- Show pending database migrations that will be applied by a deploy
- Show DNS record changes that will be applied when continuing the deploy.
- Run a task that makes sure the initial state is what you expect it to be.

#### Notes

- The reason you cannot do this as part of a CI PR is that you don't know when a PR will be merged and/or deployed, so this needs to run right before deploying.
- Potentially, this could be merged with, or could be an extension of, the current checklist functionality

Thoughts?

cc @graemej @dalehamel @thegedge @EmilS

**Comment by byroot** [comment]
Interesting. I'll sleep on it

**Comment by gmalette** [comment]
> Potentially, this could be merged with, or could be an extension of, the current checklist functionality

Could it happen after you've created the deploy but before the deployment steps are started? Why is it less than ideal?

**Comment by byroot** [comment]
Yeah the biggest issue with this is that it requires to checkout the repository which currently only happen later.

**Comment by byroot** [comment]
So after putting it some thoughts I think it's an awesome idea but it has major architectural challenges:

  - This must be backgrounded because we have a tacit rule of not shelling out nor reaching any 3rd party service from web actions.
  - Which mean you would need to trigger the check when you display the page, put some kind of spinner and update the page asynchronously.
  - You likely need a debounce / caching mechanism of some sort so that you don't overload the app by refreshing the deploys/new page.

**Comment by dalehamel** [comment]
Some back-story here - we'd like to use shipit to deploy infrastructure using [terraform](https://terraform.io/). It would be ideal if the infrastructure that a project needs were embedded directly into the repo, so that you could have a separate 'infrastructure' deploy and a separate 'code' deploy.

Before deploying the infrastructure, we want to run 'terraform plan' which will show what is expected to happen so that you can confirm and execute the plan as the actual deploy.

I don't think we can ship this without modifications to shipit-engine, unless you have some ideas @byroot @gmalette ?

Happy to discuss further.

**Comment by byroot** [comment]
> I don't think we can ship this without modifications to shipit-engine, unless you have some ideas

Not that I can think of. Except maybe doing `terraform plan`, and sleeping for a little while so that you can abort the deploy if you don't agree with the changes...

But it's kinda hacky.

Overall I like this proposal, and I think it's doable. I'll try to prototype something.

**Comment by dalehamel** [comment]
> Overall I like this proposal, and I think it's doable. I'll try to prototype something.

@byroot awesome, if there's anything we can do to help you let us know cc @Shopify/cloud. This is a big part of our road map, and I think the dream of 'shipit for infrastructure' is something that resonates well with a lot of teams.

**Comment by byroot** [comment]
Implemented in #429
