### ISSUE TITLE
Auto deploy + auto version increment for ruby gems

### ISSUE THREAD

**Issue by jasonhl** [Shopify/shipit-engine#454]
We've got a project structured as a ruby gem. On a merge to master, a hook fires to Packer. It then builds a package which is installed using ark and `gem install` via a Chef cookbook. This works reasonably well -- except when you forget to bump the version in the gemspec.

I'd like to replace all this with Shipit. When a change is merged, CI runs and if it passes, the change is auto deployed and the version auto incremented. Ideally, the cookbook bit is also replaced by the deploy process which just installs the new gem on the target box(es).

fyi: @byroot  @csfrancis

**Comment by dwradcliffe** [comment]
You could probably use https://github.com/svenfuchs/gem-release to bump the version

**Comment by byroot** [comment]
I think the rubygem supports needs a bit of polish. One thing that really sucks with the current gem release script:

Since Shipit model is to do a full clone from the local git cache for each deploy, the  `origin` remote is actually the git cache, not github. So we can't easily push tags...

cc @etiennebarrie since we were talking about it this afternoon.

It would be nice to revamp the whole thing.
