### ISSUE TITLE
Anonymous deploys and failed rollbacks

### ISSUE THREAD

**Issue by gmalette** [Shopify/shipit-engine#458]
> Anonymous deploys are caused by Shipit thinking it has deployed a version, then pings prod to fetch the versions and notices they're different. It then creates a record for the new revision, but doesn't actually deploy any code.

> This is the millionth time we've had to explain this; as an action here, can we get a UX person to come up with a better way to show this? When a rev change is detected immediately after an aborted deploy/rollback, make it show something else rather than a plain anonymous deploy...

"Anonymous" deploys are confusing for a lot of people. We also get problems where sometimes, when multiple revisions are in production, they'll flip-flop and create a few "Anonymous" deploys. 

How can we make the UX better?

**Comment by davidcornu** [comment]
Can we use `Task#user` or is that set based on the commit?

**Comment by camilo** [comment]
@davidcornu said:

Can we use Task#user or is that set based on the commit?

**Comment by byroot** [comment]
Couple mind dumps on possible fix for this (all this requires more investigation):

  - Using a distinct deploy subclass for manual deploys so that they are easier to distinguish UI wise.
  - Mark the previous deploy as "partial" if the claimed revision is exactly the last successful deploy `since_commit`

**Comment by eapache** [comment]
I like the second one. Given starting rev X, and a failed deploy to rev Y, if shipit detects rev Y in production it should simply mark the deploy as partial rather than adding an anon deploy. If it subsequently detects rev X again it should do the same. So any detected sequence of X and Y in production should do nothing but mark the failed deploy as partial (bonus: perhaps also sending an alert to spy saying "multiple revs detected in production").

**Comment by byroot** [comment]
I've put it more though:

  - If the revision check report the previous revision in the X minutes after a deploy mark it as `flapping`.
  - If the revision check report the expected revision Y times in a row, mark the deploy back to `success`.
  - Add a `retry` button to deploys in flapping state.

Both X and Y should be configurable via the `shipit.yml`.

**Comment by gmalette** [comment]
I like this
