### ISSUE TITLE
Support non-GitHub git repositories

### ISSUE THREAD

**Issue by reedloden** [Shopify/shipit-engine#462]
Seems like Shipit is very GitHub-focused, but it would be great if it could support arbitrary git repositories as well for those who don't use github.com. I know that was specifically called out in the blog announcement as a benefit to Shipit, but it also makes it less useful to a lot of other projects.

**Comment by byroot** [comment]
This have been discussed in https://github.com/Shopify/shipit-engine/issues/460.

Relying on GitHub API and webhooks simplifies Shipit architecture tremendously and we're not willing to sacrifice that.

As an example if we wanted to support BitBucket, GitLab or raw git repository, we would then need to integrate with CI providers, because none of these have an equivalent to the commit status API.

And that's just one thing out of many. I'm glad Shipit picked your interest, but it won't support anything else than GitHub anytime soon. Sorry.
