### ISSUE TITLE
Deployment time gets lost after app deployed

### ISSUE THREAD

**Issue by teu** [Shopify/shipit-engine#532]
Would be great if the deployment time could be saved and showed with the deployment. One problem we face is slow deployments at times and currently shipit shows how much time passed while looking at the deployment screen but doesn't seem to record it anywhere. This would be a very basic statistic but could lead to e.g. showing a deployment graph later on, this may be quite important for larger teams.

**Comment by gmalette** [comment]
I've also wanted this, @byroot. Our deploy time has increased dramatically recently, and at first I wanted to know if it was every deploy or just mine, and couldn't find the info in Shipit.

**Comment by byroot** [comment]
Right. We do have the data. It's a matter of dusplaying it

**Comment by byroot** [comment]
Deploy duration are now recorded and displayed since https://github.com/Shopify/shipit-engine/pull/561. I didn't cut a release yet but I will soon.

As for the graph it's still not done but I think https://github.com/Shopify/shipit-engine/issues/457 covers it as well and I prefer to have a single issue.
