### ISSUE TITLE
[Question] Should the UI be changed to use a different css framework and/or templating engine?

### ISSUE THREAD

**Issue by perobertson** [Shopify/shipit-engine#558]
Ive seen some discussion about using [bootstrap](http://getbootstrap.com/) and [primer](http://primercss.io/). Is this something that is still wanted?

There has also been some discussion about switching to [slim](http://slim-lang.com/) over erb. Is this something that is still wanted?

See #469 for some of the discussion that has occurred.

**Comment by byroot** [comment]
> Ive seen some discussion about using bootstrap and primer. Is this something that is still wanted?

Yes. Design work keep being an issue in the project and being able to implement clean UI with little to no CSS would be a huge benefit.

> There has also been some discussion about switching to slim over erb

I'm in favor of it but it's a relatively more controversial change, so probably not.

**Comment by perobertson** [comment]
> with little to no CSS
So you do not want to go down the bootstrap route or did you just mean no custom css being made?

**Comment by byroot** [comment]
> So you do not want to go down the bootstrap route or did you just mean no custom css being made?

Sorry I realize it wasn't very clear.

We're quite happy with the current design, and we'd like to keep it.
But since it's homemade CSS it requires skills that I and most Shipit contributors don't have to add new UI.

So the idea behind #469 was to develop a custom Bootstrap theme so that we can keep the current look and feel of Shipit, but make it easy to implement new interfaces.

**Comment by perobertson** [comment]
Gotcha. Ive been meaning to do some work on the UI side and just wanted to figure out the direction you were going with that.

So the next question is should a CDN be used instead of having shipit host the css?

**Comment by byroot** [comment]
>  Ive been meaning to do some work on the UI side and just wanted to figure out the direction you were going with that.

And it's very much appreciated :) #448 was such a shame, thanks again for fixing it.

So if you want to do more UI work on Shipit:

  - If you think you have **a lot** of time to commit you can attempt the Bootstrap conversion, but beware it's not simple nor fast.
  - If you just have a few hours there and there, I have no problem merging PRs going forward with the current CSS.

> So the next question is should a CDN be used instead of having shipit host the css?

Since Shipit is a rails engine it's up to the host application to decide such thing. There is many ways to serve assets, and Sprockets let you chose the one you prefer.

**Comment by byroot** [comment]
Closing this. Feel free to re-open if you have more questions.
