### ISSUE TITLE
Support new Checks API

### ISSUE THREAD

**Issue by sgringwe** [Shopify/shipit-engine#808]
It would be great to support the new https://developer.github.com/v3/checks/runs/ Checks API, which is used by Github Apps such as Google Cloud Build (https://blog.github.com/2018-07-26-simplify-your-ci-process/).

Currently, Shipit does not seem to detect the checks statuses and so does not show it in the UI either.

**Comment by byroot** [comment]
Could you clarify what you have in mind? I'm aware of the checks API, but don't really see what Shipit misses.

Do you mean that checks are not visible in Shipit?

**Comment by sgringwe** [comment]
@byroot correct - when switching from having our container builder update the commit status, to having the new Cloud Build app use the Checks feature, it no longer is showing up in the commit status on the "Commits" page. it also seams that the Continuous Deployment feature is not aware of the Check, since it will auto-deploy before the check passes.

**Comment by casperisfine** [comment]
I though they appeared as regular statuses, but it seems it's not the case.

At first sight, it seems we can simply fetch (and listen to hooks) both. Shouldn't be too hard, but it will require some refactor to group statuses and checks together.

We'll soon be using checks internally, so it's very likely I'll work on this soonish (can't promise any ETA).

**Comment by Strech** [comment]
I think this case is now valid. When you switch TravisCI to be a Github Application Shipit can't read commits build statuses. And the only 2 ways to fix it – emergency mode or cancel CI checks.

**Comment by casperisfine** [comment]
Yes, we're being impacted by this as well. Still can't promise any ETA but I can tell you this is high priority for Shopify, so hopefully I should be able to come up with a fix very soon.

**Comment by Strech** [comment]
@casperisfine thanks for the reply ❤️ If I can help somehow – just let me know

**Comment by casperisfine** [comment]
Ok, so I started a rough prototype of that feature (https://github.com/Shopify/shipit-engine/pull/817) have some good, and some fairly news.

The good news is that overall it seems doable to make some compatibility layer between checks and statuses, so that Shipit can treat boths the same way:
<img width="483" alt="capture d ecran 2018-10-10 a 16 26 06" src="https://user-images.githubusercontent.com/19192189/46764020-5016a200-cca9-11e8-8efb-da6d14743b12.png">

The other good news is that It doesn't seem that much work at first sight, I still don't want to commit to any ETA because I have some stuffs I need to attend to next week.

Now the bad news, there is one nasty blocker, the GitHub API endpoint needed for this doesn't allow GitHub Apps, I'm currently building that proto using a Personal Token hoping GitHub will change this. I'm still waiting on a response from support.

**Comment by casperisfine** [comment]
#817 is now awaiting review. You are also welcome to test it (make sure to point to a clone of the repo as I might for push that PR branch).
